@extends('layouts.dashboard')
@section('title', 'Parent Report')

@php
    $attendanceSummary = $report->attendance_summary ?? [];
    $homeworkSummary = $report->homework_summary ?? [];
    $quizSummary = $report->quiz_summary ?? [];
    $badgeSummary = $report->badge_summary ?? [];
@endphp

@section('content')
<div class="space-y-8">
    <section class="rounded-[2rem] border border-white/70 bg-white/95 px-6 py-8 shadow-2xl shadow-slate-950/10 sm:px-8">
        <p class="text-xs font-semibold uppercase tracking-[0.3em] text-slate-400">Parent report</p>
        <h1 class="mt-3 text-3xl font-black tracking-tight text-slate-900">{{ $report->student?->displayName() ?? 'Student report' }}</h1>
        <p class="mt-3 text-sm leading-6 text-slate-600">
            Period {{ optional($report->report_period_start)->format('M j, Y') ?? 'Start' }} to {{ optional($report->report_period_end)->format('M j, Y') ?? 'End' }}.
            Generated by {{ $report->generator?->displayName() ?? 'Teacher' }}.
        </p>
    </section>

    <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <div class="rounded-3xl border border-slate-200 bg-white/90 p-5 shadow-sm">
            <p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Attendance</p>
            <p class="mt-3 text-3xl font-black text-slate-900">{{ $attendanceSummary['present'] ?? 0 }}/{{ $attendanceSummary['total'] ?? 0 }}</p>
        </div>
        <div class="rounded-3xl border border-slate-200 bg-white/90 p-5 shadow-sm">
            <p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Homework</p>
            <p class="mt-3 text-3xl font-black text-slate-900">{{ $homeworkSummary['reviewed'] ?? 0 }}/{{ $homeworkSummary['total'] ?? 0 }}</p>
        </div>
        <div class="rounded-3xl border border-slate-200 bg-white/90 p-5 shadow-sm">
            <p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Quiz average</p>
            <p class="mt-3 text-3xl font-black text-slate-900">{{ round((float) ($quizSummary['avg_score'] ?? 0)) }}%</p>
        </div>
        <div class="rounded-3xl border border-slate-200 bg-white/90 p-5 shadow-sm">
            <p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Points</p>
            <p class="mt-3 text-3xl font-black text-slate-900">{{ $badgeSummary['points'] ?? 0 }}</p>
        </div>
    </section>

    <section class="grid gap-6 xl:grid-cols-3">
        <div class="rounded-[2rem] border border-slate-200 bg-white/95 p-6 shadow-sm xl:col-span-2">
            <h2 class="text-lg font-bold text-slate-900">Teacher comments</h2>
            <div class="mt-5 rounded-3xl bg-slate-50 px-4 py-4">
                <p class="whitespace-pre-line text-sm leading-6 text-slate-700">{{ $report->teacher_comments ?: 'No teacher comments were added.' }}</p>
            </div>

            @if ($report->ai_summary)
                <div class="mt-5 rounded-3xl bg-indigo-50 px-4 py-4 text-indigo-900">
                    <p class="text-xs font-semibold uppercase tracking-[0.2em] text-indigo-500">AI summary</p>
                    <p class="mt-2 whitespace-pre-line text-sm leading-6">{{ $report->ai_summary }}</p>
                </div>
            @endif

            <div class="mt-5 rounded-3xl bg-emerald-50 px-4 py-4 text-emerald-900">
                <p class="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-600">Parent recommendation</p>
                <p class="mt-2 whitespace-pre-line text-sm leading-6">{{ $report->parent_recommendation ?: 'No recommendation provided.' }}</p>
            </div>
        </div>

        <div class="rounded-[2rem] border border-slate-200 bg-white/95 p-6 shadow-sm">
            <h2 class="text-lg font-bold text-slate-900">Summary</h2>
            <div class="mt-5 space-y-4 text-sm">
                <div class="rounded-2xl bg-slate-50 px-4 py-4">
                    <p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Attendance breakdown</p>
                    <p class="mt-2 text-slate-700">Present {{ $attendanceSummary['present'] ?? 0 }}, absent {{ $attendanceSummary['absent'] ?? 0 }}, late {{ $attendanceSummary['late'] ?? 0 }}.</p>
                </div>
                <div class="rounded-2xl bg-slate-50 px-4 py-4">
                    <p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Homework breakdown</p>
                    <p class="mt-2 text-slate-700">Submitted {{ $homeworkSummary['submitted'] ?? 0 }}, reviewed {{ $homeworkSummary['reviewed'] ?? 0 }}.</p>
                </div>
                <div class="rounded-2xl bg-slate-50 px-4 py-4">
                    <p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Badges</p>
                    <div class="mt-3 flex flex-wrap gap-2">
                        @forelse ($badgeSummary['badges'] ?? [] as $badge)
                            <span class="rounded-full bg-white px-3 py-1 text-xs font-semibold text-slate-700 shadow-sm">{{ $badge['name'] ?? 'Badge' }}</span>
                        @empty
                            <span class="text-slate-500">No badges included.</span>
                        @endforelse
                    </div>
                </div>
            </div>

            <div class="mt-5 flex flex-wrap gap-3">
                <x-primary-button href="{{ route('parent-portal.dashboard', ['child_id' => $report->student_id]) }}">
                    Back to portal
                </x-primary-button>
                <x-secondary-button href="{{ route('academic.reports.index') }}">
                    All reports
                </x-secondary-button>
            </div>
        </div>
    </section>
</div>
@endsection
